# Generated by Django 2.2.17 on 2021-03-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi_score', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='youtubelink',
            new_name='ytlink',
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='hi_score.Genre'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
