# Generated by Django 2.2.17 on 2021-03-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi_score', '0002_auto_20210319_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ytlink',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
